apiVersion: v1
kind: Pod
metadata:
  name: storage-demo
spec:
  initContainers:
    - name: con1
      image: centos
      volumeMounts:
      - mountPath: /parameters
        name: temp
  containers:
    - name: con2
      image: centos
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
      - mountPath: /parameters
        name: temp
  volumes:
  - name: temp
    emptyDir:
      sizeLimit: 5Mi