apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  serviceAccountName: frontend
  containers:
    - name: frontend
      image: 624783896224.dkr.ecr.us-east-1.amazonaws.com/frontend
  imagePullSecrets:
    - name: aws-ecr

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  serviceAccountName: backend
  containers:
    - name: backend
      image: 624783896224.dkr.ecr.us-east-1.amazonaws.com/backend
      env:
        - name: DB_HOST
          value: dev-mysql.cluster-cguk3dhtfjx0.us-east-1.rds.amazonaws.com
  imagePullSecrets:
    - name: aws-ecr
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Expense@1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: schema
---
apiVersion: batch/v1
kind: Job
metadata:
  name: schema
spec:
  template:
    spec:
      serviceAccountName: schema
      imagePullSecrets:
        - name: aws-ecr
      restartPolicy: Never
      containers:
      - name: schema
        image: 624783896224.dkr.ecr.us-east-1.amazonaws.com/expense-schema-load
        env:
        - name: DBHOST
          value: dev-mysql.cluster-cguk3dhtfjx0.us-east-1.rds.amazonaws.com
        - name: DBPASS
          value: "expensedev1234"
        - name: DBUSER
          value: mysqlrdsadmin
        - name: COMPONENT
          value: backend